### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by UnderKoen** [shlaikov/intellij-bpmn2-plugin#8]
I just tried installing this plugin, it looked awesome. But I had some problems getting it to work. When trying to open an bpmn file it loads forever.

Webstorm 2023.1.2

**Comment by shlaikov** [comment]
@UnderKoen very happy to see the first issue in this repository. I tried to install via marketplace, there really is such a problem. Due to the fact that GitHub Action do not collect static files(`yarn && yarn build`) when the plug-in is released.


I'll sort this problem out asap and will inform you.

**Comment by shlaikov** [comment]
@UnderKoen with [this](https://github.com/shlaikov/intellij-bpmn2-plugin/releases/tag/v0.3.1) hotfix your problem will go away. The marketplace will usually give confirmation in one or two days if I released it today.

Thank you for being vigilant.

PS. If everything goes well, then I would be pleased to receive a **star** in repo 😄
